---
points:
  marker_0:
    - [-0.28, -0.75]
    - [0.60, 0, 0, -0.79]
  marker_1:
    - [-1.7, -5]
    - [0.65, 0, 0, -0.75]
  marker_2:
    - [-5.59, -5.31]
    - [-0.13, 0, 0, -1]
  marker_3:
    - [-4.19, -5.64]
    - [-0.99, 0, 0, 0.12]
  marker_4:
    - [-0.83, -1.93]
    - [-0.77, 0, 0, -0.63]
  marker_5:
    - [-4.71, 1.77]
    - [-0.11, 0, 0, -1]
